import type { Locale } from './content';

export const clientCopy = {
  en: {
    qualityEyebrow: 'Care built in', qualityTitle: 'Useful software. Built with care.',
    qualityIntro: 'A small project deserves the same attention to quality and security as a larger one.',
    quality: [
      { title: 'Quality you can try', text: 'Important journeys are tested before delivery. You get to try the result, so we can check that it does the job you agreed to.' },
      { title: 'Security from the start', text: 'Automated checks help spot risky changes and outdated software. Access and data needs are considered as part of the project—not left until the end.' },
      { title: 'A responsible handover', text: 'Changes are reviewed before they ship. You know who built the work, how to use it and what ongoing care has been agreed.' },
    ],
    qualityScope: 'Checks are chosen for each project; they are not a certification or a promise of flawless software. Maintenance, backups and support are agreed separately.',
    portfolioBridge: 'Websites, small apps, reusable tools and earlier research. Explore the full range of work behind Devantler Tech.',
    projectsIntro: 'Different projects. The same care for the people who use them.',
    familyLabel: '01 / Websites & small apps', catalogueLabel: '02 / The wider portfolio', researchLabel: '03 / Earlier research',
    catalogueTitle: 'Tools that make other work possible.',
    catalogueIntro: 'Alongside websites and small apps, I build tools for developing, checking and running software. Here is the complete public collection, including work still in development.',
    reuse: 'Availability does not grant unrestricted reuse. Each project has its own licence; the labels below identify special restrictions. No paid product subscription is available.',
    qualityBridge: 'How the work is built', qualityAction: 'Quality & security on Home',
    platformTitle: 'The hosting behind my own apps',
    platformText: 'A separate project for running and maintaining my own applications. It is not a hosting guarantee; client capacity, support and running costs are agreed individually.',
    researchText: 'My master’s research looked at how organisations could share useful data while keeping responsibility for their own part. It is background research, not a current service.',
    details: 'Research background & diagram (English)',
    researchBackground: 'Data products & data spaces',
    researchBackgroundText: 'The work explored independent data products working together in a data space, with a prototype built in .NET. The thesis sets out the investigation and its trade-offs.',
    researchDiagram: 'How independent data products can fit together',
    productVisit: 'Explore KSail', journal: 'Stories behind the work (English)',
  },
  da: {
    qualityEyebrow: 'Omtanke fra starten', qualityTitle: 'Nyttig software. Bygget med omtanke.',
    qualityIntro: 'Et lille projekt fortjener samme omtanke for kvalitet og sikkerhed som et større.',
    quality: [
      { title: 'Kvalitet, du kan afprøve', text: 'Vigtige brugerforløb testes før levering. Du får mulighed for at afprøve resultatet, så vi kan kontrollere, at det løser den aftalte opgave.' },
      { title: 'Sikkerhed fra starten', text: 'Automatiske kontroller hjælper med at opdage risikable ændringer og forældet software. Adgang og databehov tænkes ind i projektet—ikke først til sidst.' },
      { title: 'En ansvarlig overdragelse', text: 'Ændringer gennemgås før udgivelse. Du ved, hvem der har bygget løsningen, hvordan den bruges, og hvilken løbende vedligeholdelse der er aftalt.' },
    ],
    qualityScope: 'Kontrollen vælges til hvert projekt; den er ikke en certificering eller et løfte om fejlfri software. Vedligeholdelse, backup og support aftales særskilt.',
    portfolioBridge: 'Hjemmesider, små apps, genbrugelige værktøjer og tidligere forskning. Se bredden i arbejdet bag Devantler Tech.',
    projectsIntro: 'Forskellige projekter. Samme omtanke for dem, der bruger dem.',
    familyLabel: '01 / Hjemmesider og små apps', catalogueLabel: '02 / Den bredere portefølje', researchLabel: '03 / Tidligere forskning',
    catalogueTitle: 'Værktøjer, der gør andet arbejde muligt.',
    catalogueIntro: 'Ud over hjemmesider og små apps bygger jeg værktøjer til at udvikle, kontrollere og drive software. Her er hele den offentlige samling, også projekter under udvikling.',
    reuse: 'Tilgængelighed giver ikke ubegrænset ret til genbrug. Hvert projekt har sin egen licens; mærkaterne nedenfor viser særlige begrænsninger. Der tilbydes ingen betalte produktabonnementer.',
    qualityBridge: 'Sådan bliver arbejdet bygget', qualityAction: 'Kvalitet og sikkerhed på forsiden',
    platformTitle: 'Hostingen bag mine egne apps',
    platformText: 'Et særskilt projekt til at drive og vedligeholde mine egne applikationer. Det er ikke en hostinggaranti; kapacitet, support og driftsudgifter aftales for hvert kundeprojekt.',
    researchText: 'Mit speciale undersøgte, hvordan organisationer kunne dele nyttige data og stadig have ansvaret for deres egen del. Det er baggrundsforskning, ikke en aktuel ydelse.',
    details: 'Forskningsbaggrund og diagram (engelsk)',
    researchBackground: 'Data products & data spaces',
    researchBackgroundText: 'The work explored independent data products working together in a data space, with a prototype built in .NET. The thesis sets out the investigation and its trade-offs.',
    researchDiagram: 'How independent data products can fit together',
    productVisit: 'Se mere om KSail', journal: 'Historierne bag arbejdet (engelsk)',
  },
} as const;

// Business descriptions complement the technical catalogue without changing
// its repository set, ranking, licence dispositions or technical routes.
export const clientProducts: Record<string, Record<Locale, string>> = {
  ksail: { en: 'One tool for setting up and running software environments, with an optional AI assistant.', da: 'Ét værktøj til at oprette og drive softwaremiljøer med en valgfri AI-assistent.' },
  'world-at-ruin': { en: 'An online fantasy game in early development. A creative project, not a finished game; reuse and hosting are restricted by its licence.', da: 'Et online fantasyspil i tidlig udvikling. Et kreativt projekt, ikke et færdigt spil; licensen begrænser genbrug og hosting.' },
  'data-product-controller': { en: 'Tools for describing, combining and publishing reusable data products.', da: 'Værktøjer til at beskrive, kombinere og udgive genbrugelige dataprodukter.' },
  'agent-plugins': { en: 'Installable bundles that give AI coding assistants a consistent way of working.', da: 'Pakker, der giver AI-kodeassistenter en ensartet måde at arbejde på.' },
  'agent-skills': { en: 'Focused instructions that help AI assistants carry out development tasks with care.', da: 'Afgrænsede instruktioner, der hjælper AI-assistenter med at løse udviklingsopgaver med omtanke.' },
  'provider-upjet-unifi': { en: 'A reusable connection for managing supported UniFi network equipment through an infrastructure platform.', da: 'En genbrugelig forbindelse til at administrere understøttet UniFi-netværksudstyr via en infrastrukturplatform.' },
  '.github': { en: 'Shared automation for building, checking and releasing software across the portfolio.', da: 'Fælles automatisering til at bygge, kontrollere og udgive software på tværs af porteføljen.' },
  actions: { en: 'The earlier automation collection, retained for existing users. New projects use the current .github collection.', da: 'Den tidligere samling af automatisering, bevaret for eksisterende brugere. Nye projekter bruger den aktuelle .github-samling.' },
  'kyverno-policies': { en: 'Tested rules that help keep application hosting consistent and controlled.', da: 'Testede regler, der hjælper med at holde applikationshosting ensartet og kontrolleret.' },
  'go-template': { en: 'A prepared starting point for a new software project built in Go.', da: 'Et forberedt udgangspunkt for et nyt softwareprojekt bygget i Go.' },
  'dotnet-template': { en: 'A prepared starting point for .NET software, with conventions and automatic checks.', da: 'Et forberedt udgangspunkt for .NET-software med fælles rammer og automatiske kontroller.' },
  'platform-template': { en: 'A reusable starting point for building an application-hosting platform—not a copy of a live installation.', da: 'En genbrugelig startpakke til en platform for applikationshosting, ikke en kopi af en aktiv installation.' },
  'platform-tenant-template': { en: 'A reusable starting point for putting an application on a hosting platform.', da: 'Et genbrugeligt udgangspunkt for at lægge en applikation på en hostingplatform.' },
};
